usagePlan:
  throttle:
    rateLimit: 20
    burstLimit: 40

  quota:
    limit: 10000
    period: DAY

consumers:
  web:
    description: Front-end web
    enabled: true

  mobile:
    description: Aplicativo mobile
    enabled: true

  ci:
    description: Contract test da pipeline
    enabled: true

stage:
  throttle:
    rateLimit: 50
    burstLimit: 100

  detailedMetrics: false

  loggingLevel: INFO

  dataTrace: false

  accessLogRetentionDays: 3

waf:
  enabled: false
  rateLimit: 2000
